version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      radix-ui:
        patterns:
          - '@radix-ui/*'
      types:
        patterns:
          - '@types/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    reviewers:
      - 'security-team'
