events {
    worker_connections 1024;
}

http {
    # Time limits
    proxy_read_timeout 60;
    proxy_connect_timeout 60;
    proxy_send_timeout 60;

    # Upstreams
    upstream patient_portal     { server localhost:3000; }
    upstream doctor_portal      { server localhost:3001; }
    upstream hospital_hms       { server localhost:3002; }
    upstream admin_panel        { server localhost:3003; }
    upstream api_gateway        { server localhost:4002; }
    upstream auth_service       { server localhost:4001; }

    # ---- Dev Server (Localhost) ----
    server {
        listen 8080; # Dev port to avoid conflict with standard HTTP
        server_name localhost;

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://api_gateway/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://patient_portal;
            proxy_set_header Host $host;
        }
    }
}
