export enum BloodBankEventType {
  BLOOD_REQUEST_CREATED = 'BLOOD_REQUEST_CREATED',
  CROSSMATCH_STARTED = 'CROSSMATCH_STARTED',
  CROSSMATCH_COMPLETED = 'CROSSMATCH_COMPLETED',
  CROSSMATCH_FAILED = 'CROSSMATCH_FAILED',
  EMERGENCY_BLOOD_OVERRIDE_APPROVED = 'EMERGENCY_BLOOD_OVERRIDE_APPROVED',
  BLOOD_ALLOCATED = 'BLOOD_ALLOCATED',
  BLOOD_ISSUED = 'BLOOD_ISSUED',
  TRANSFUSION_STARTED = 'TRANSFUSION_STARTED',
  TRANSFUSION_PAUSED = 'TRANSFUSION_PAUSED',
  TRANSFUSION_COMPLETED = 'TRANSFUSION_COMPLETED',
  TRANSFUSION_STOPPED = 'TRANSFUSION_STOPPED',
  TRANSFUSION_REACTION_RECORDED = 'TRANSFUSION_REACTION_RECORDED',
  TRANSFUSION_REACTION_ACKNOWLEDGED = 'TRANSFUSION_REACTION_ACKNOWLEDGED',
  BLOOD_REQUEST_CANCELLED = 'BLOOD_REQUEST_CANCELLED',
}

export interface BloodBankEvent {
  eventId: string;
  eventType: BloodBankEventType;
  executionId?: string;
  orderId?: string;
  bloodUnitId?: string;
  issueId?: string;
  episodeId?: string;
  reactionId?: string;
  hospitalId: string;
  patientId: string;
  timestamp: Date;
  payload: any;
}
