export enum DomainAction {
  PATIENT_SAFETY_SUMMARY_READ = 'PATIENT_SAFETY_SUMMARY_READ',
  PATIENT_LONGITUDINAL_HISTORY_READ = 'PATIENT_LONGITUDINAL_HISTORY_READ',
  CLINICAL_RECORD_CREATE = 'CLINICAL_RECORD_CREATE',
  CLINICAL_RECORD_AMEND = 'CLINICAL_RECORD_AMEND',
  CARE_TEAM_ASSIGN = 'CARE_TEAM_ASSIGN',
  CARE_TEAM_REMOVE = 'CARE_TEAM_REMOVE',
  CARE_TRANSFER_INITIATE = 'CARE_TRANSFER_INITIATE',
  CARE_TRANSFER_REVIEW = 'CARE_TRANSFER_REVIEW',
  CARE_TRANSFER_ACCEPT = 'CARE_TRANSFER_ACCEPT',
  BREAK_GLASS_ACTIVATE = 'BREAK_GLASS_ACTIVATE',
  IDENTITY_MERGE_REQUEST = 'IDENTITY_MERGE_REQUEST',
  IDENTITY_MERGE_REVIEW = 'IDENTITY_MERGE_REVIEW',
  IDENTITY_MERGE_APPROVE = 'IDENTITY_MERGE_APPROVE',
  IDENTITY_MERGE_EXECUTE = 'IDENTITY_MERGE_EXECUTE',

  // Phase 3 Actions
  CLINICAL_DISCHARGE_DECISION = 'CLINICAL_DISCHARGE_DECISION',
  DISCHARGE_PROCESS_MUTATION = 'DISCHARGE_PROCESS_MUTATION',
  LAMA_INITIATE = 'LAMA_INITIATE',
  LAMA_DOCUMENT = 'LAMA_DOCUMENT',
  LAMA_WITHDRAW = 'LAMA_WITHDRAW',
  ABSENCE_SUSPECT = 'ABSENCE_SUSPECT',
  ABSENCE_RESOLVE = 'ABSENCE_RESOLVE',
  DEPARTURE_CONFIRM_STANDARD = 'DEPARTURE_CONFIRM_STANDARD',
  DEPARTURE_CONFIRM_LAMA = 'DEPARTURE_CONFIRM_LAMA',
  DEPARTURE_CONFIRM_WITHOUT_NOTICE = 'DEPARTURE_CONFIRM_WITHOUT_NOTICE',

  // Phase 5 Actions
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_COMPLETE = 'ORDER_COMPLETE',
  ORDER_OVERRIDE_CDS = 'ORDER_OVERRIDE_CDS',
  ORDER_EXECUTION_UPDATE = 'ORDER_EXECUTION_UPDATE',

  // Phase 5B Actions
  LAB_RESULT_ENTRY = 'LAB_RESULT_ENTRY',
  LAB_RESULT_VERIFY = 'LAB_RESULT_VERIFY',

  // Phase 5B.3 Radiology Actions
  RADIOLOGY_ORDER = 'RADIOLOGY_ORDER',
  RADIOLOGY_SCHEDULE = 'RADIOLOGY_SCHEDULE',
  RADIOLOGY_ACCESSION = 'RADIOLOGY_ACCESSION',
  RADIOLOGY_ACQUIRE = 'RADIOLOGY_ACQUIRE',
  RADIOLOGY_REPORT_DRAFT = 'RADIOLOGY_REPORT_DRAFT',
  RADIOLOGY_REPORT_VERIFY = 'RADIOLOGY_REPORT_VERIFY',
  RADIOLOGY_VIEW = 'RADIOLOGY_VIEW',

  // Phase 5B.4 Procedure Actions
  PROCEDURE_SCHEDULE = 'PROCEDURE_SCHEDULE',
  PROCEDURE_START = 'PROCEDURE_START',
  PROCEDURE_COMPLETE = 'PROCEDURE_COMPLETE',
  PROCEDURE_REPORT_DRAFT = 'PROCEDURE_REPORT_DRAFT',
  PROCEDURE_REPORT_FINAL = 'PROCEDURE_REPORT_FINAL',
  PROCEDURE_CANCEL = 'PROCEDURE_CANCEL',

  // Phase 5B.5 Blood Bank Actions
  BLOOD_REQUEST_CREATE = 'BLOOD_REQUEST_CREATE',
  BLOOD_CROSSMATCH = 'BLOOD_CROSSMATCH',
  BLOOD_ALLOCATE = 'BLOOD_ALLOCATE',
  BLOOD_ISSUE = 'BLOOD_ISSUE',
  TRANSFUSION_START = 'TRANSFUSION_START',
  TRANSFUSION_COMPLETE = 'TRANSFUSION_COMPLETE',
  TRANSFUSION_REACTION = 'TRANSFUSION_REACTION',
  // Phase 5B.6 Referral Actions
  REFERRAL_CREATE = 'REFERRAL_CREATE',
  REFERRAL_SEND = 'REFERRAL_SEND',
  REFERRAL_ACCEPT = 'REFERRAL_ACCEPT',
  REFERRAL_DECLINE = 'REFERRAL_DECLINE',
  REFERRAL_COMPLETE = 'REFERRAL_COMPLETE',
  REFERRAL_CANCEL = 'REFERRAL_CANCEL',
  CARE_TRANSFER_REQUEST = 'CARE_TRANSFER_REQUEST',
  CARE_TRANSFER_EXECUTE = 'CARE_TRANSFER_EXECUTE',
  CONSULTATION_COMPLETE = 'CONSULTATION_COMPLETE',

  // Phase 9B Pharmacy Actions
  PHARMACY_VIEW = 'PHARMACY_VIEW',
  PHARMACY_VERIFY = 'PHARMACY_VERIFY',
  PHARMACY_DISPENSE = 'PHARMACY_DISPENSE',
  PHARMACY_CANCEL = 'PHARMACY_CANCEL',
}

export interface ActorContext {
  id: string; // Doctor ID, Staff ID, or UserAccount ID
  hospitalId?: string; // Optional, as some actions are cross-hospital or platform-wide
  role: string; // e.g., 'DOCTOR', 'NURSE', 'SUPER_ADMIN'
  permissions?: string[]; // E.g., ['module:IDENTITY', 'action:EXECUTE']
}

export interface ResourceContext {
  patientId?: string;
  episodeId?: string; // Visit or Admission ID
  hospitalId?: string; // Originating hospital of the resource
  targetId?: string; // E.g. Record ID being amended, merge request ID
}

export interface AuthorizeRequest {
  actor: ActorContext;
  action: DomainAction;
  resource: ResourceContext;
}

export enum AuthorizationDecision {
  ALLOW = 'ALLOW',
  DENY = 'DENY',
  BREAK_GLASS = 'BREAK_GLASS', // Allowed due to active Break-Glass
}

export interface AuthorizationResult {
  decision: AuthorizationDecision;
  reason: string;
  auditLogId?: string;
}

export interface IAuthorizationService {
  authorize(req: AuthorizeRequest): Promise<AuthorizationResult>;
  getStaffPermissions(userId: string, role: string): Promise<string[]>;
  hasCapability(permissions: string[], requiredModule: string): boolean;
}
