export enum Permission {
  // Patient
  PATIENT_VIEW = 'PATIENT_VIEW',
  PATIENT_EDIT = 'PATIENT_EDIT',

  // Appointments
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_VIEW = 'APPOINTMENT_VIEW',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',

  // Consultations
  CONSULTATION_CREATE = 'CONSULTATION_CREATE',
  CONSULTATION_VIEW = 'CONSULTATION_VIEW',

  // EMR
  EMR_VIEW = 'EMR_VIEW',
  EMR_EDIT = 'EMR_EDIT',

  // Schedule
  SCHEDULE_VIEW = 'SCHEDULE_VIEW',
  SCHEDULE_MANAGE = 'SCHEDULE_MANAGE',

  // Billing
  BILLING_VIEW = 'BILLING_VIEW',
  BILLING_EDIT = 'BILLING_EDIT',

  // Doctors
  DOCTOR_VIEW = 'DOCTOR_VIEW',
  DOCTOR_MANAGE = 'DOCTOR_MANAGE',

  // Hospital
  HOSPITAL_SETTINGS = 'HOSPITAL_SETTINGS',

  // Reports & Analytics
  REPORTS_VIEW = 'REPORTS_VIEW',
}
