"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _patient_profile_card from './patient-profile-card.bones.json'
import _vitals_quick_stats from './vitals-quick-stats.bones.json'
import _vitals_history from './vitals-history.bones.json'
import _medications_list from './medications-list.bones.json'
import _prescriptions_list from './prescriptions-list.bones.json'
import _vaccinations_list from './vaccinations-list.bones.json'
import _maternal_health_hero from './maternal-health-hero.bones.json'
import _wallet_header from './wallet-header.bones.json'
import _transaction_history from './transaction-history.bones.json'
import _personal_data_grid from './personal-data-grid.bones.json'
import _records_list from './records-list.bones.json'
import _hospital_stats_grid from './hospital-stats-grid.bones.json'
import _recent_visits_table from './recent-visits-table.bones.json'
import _lab_stats_grid from './lab-stats-grid.bones.json'
import _lab_orders_list from './lab-orders-list.bones.json'
import _lab_catalog_overview from './lab-catalog-overview.bones.json'
import _admin_stats_grid from './admin-stats-grid.bones.json'
import _platform_growth_card from './platform-growth-card.bones.json'
import _agent_stats_grid from './agent-stats-grid.bones.json'
import _agent_hospitals_list from './agent-hospitals-list.bones.json'
import _agent_patients_list from './agent-patients-list.bones.json'

registerBones({
  "patient-profile-card": _patient_profile_card,
  "vitals-quick-stats": _vitals_quick_stats,
  "vitals-history": _vitals_history,
  "medications-list": _medications_list,
  "prescriptions-list": _prescriptions_list,
  "vaccinations-list": _vaccinations_list,
  "maternal-health-hero": _maternal_health_hero,
  "wallet-header": _wallet_header,
  "transaction-history": _transaction_history,
  "personal-data-grid": _personal_data_grid,
  "records-list": _records_list,
  "hospital-stats-grid": _hospital_stats_grid,
  "recent-visits-table": _recent_visits_table,
  "lab-stats-grid": _lab_stats_grid,
  "lab-orders-list": _lab_orders_list,
  "lab-catalog-overview": _lab_catalog_overview,
  "admin-stats-grid": _admin_stats_grid,
  "platform-growth-card": _platform_growth_card,
  "agent-stats-grid": _agent_stats_grid,
  "agent-hospitals-list": _agent_hospitals_list,
  "agent-patients-list": _agent_patients_list,
})
